// Assembles the in-memory GraphFile the app renders — cards/themes/edges — from
// raw pieces fetched straight from data/ (no pre-built graph file, no server-side
// merge step; see README for why: "graph should be generated by visualizer, not in
// advance by some server script"). Ported 1:1 from the old scripts/build-graph.mjs,
// which this replaces.
//
// Creature subtypes (Human, Goblin, Dragon, ...) get their THEME auto-generated —
// derived fresh from type_line every load (see creatureSubtypes below), never listed
// in data/global_themes.json, so the theme checklist/graph knows Human/Goblin/etc. exist
// without anyone hand-adding them. Their EDGES are not automatic though: which card
// produces/consumes a creature-type theme, and at what weight, is a normal tagging
// call the agent makes and writes to <set>_relations.json, same as any curated
// theme — this module only derives the theme id/label, never the per-card edge.
// data/type_themes.json is the same id -> label list, persisted for reference (so an
// agent tagging a card can look up what creature-type ids already exist) — not read
// here, this module derives labels itself straight from type_line.
//
// Cards with no entry yet in <set>_relations.json get the "Not Processed" fallback
// (same as an entry that turned out to genuinely match nothing) so the graph still
// renders meaningfully while tagging is in progress — independent of (and additive
// with) any creature-type edges the card also gets.

import type { CardData, EdgeData, GraphFile, Role, ThemeData } from '../types';

// Loosely typed — only the Scryfall fields this module actually reads.
export interface ScryfallCard {
  id: string;
  name: string;
  cmc?: number;
  colors?: string[];
  color_identity?: string[];
  type_line?: string;
  rarity?: string;
  scryfall_uri: string;
  keywords?: string[];
  digital?: boolean;
  image_uris?: { normal: string };
  card_faces?: { colors?: string[]; type_line?: string; keywords?: string[]; image_uris?: { normal: string } }[];
  all_parts?: { id: string; component: string }[];
}

export type TokensById = Record<string, { name: string; image: string | null }>;

export interface RelationsEntry {
  name: string;
  themes: Partial<Record<Role, Record<string, number>>>;
}

// Evergreen / combat keywords -> rendered as badges on the card node, not graph edges.
const BADGE_KEYWORDS = new Set([
  'Flying', 'Trample', 'Vigilance', 'Reach', 'Menace', 'Deathtouch', 'Haste',
  'Lifelink', 'Ward', 'Indestructible', 'Flash', 'Crew', 'First strike', 'Double strike',
  'Hexproof', 'Defender',
]);

// Single-faced (and split/adventure, which share one image at the top level) cards
// return one URL; true double-faced cards (each face has its own image_uris) return
// both, front first, so the UI can show both sides on hover.
function cardImages(card: ScryfallCard): string[] {
  if (card.image_uris) return [card.image_uris.normal];
  return (card.card_faces || []).filter((f) => f.image_uris).map((f) => f.image_uris!.normal);
}

function cardKeywords(card: ScryfallCard): string[] {
  const kws = new Set(card.keywords || []);
  for (const f of card.card_faces || []) for (const k of f.keywords || []) kws.add(k);
  return [...kws];
}

function cardTokens(card: ScryfallCard, tokensById: TokensById): { name: string; image: string }[] {
  const seen = new Set<string>();
  const tokens: { name: string; image: string }[] = [];
  for (const p of card.all_parts || []) {
    if (p.component !== 'token' || seen.has(p.id)) continue;
    seen.add(p.id);
    const t = tokensById[p.id];
    if (t?.image) tokens.push({ name: t.name, image: t.image });
  }
  return tokens;
}

// "Legendary Creature — Human Knight" -> ["Human", "Knight"]. Reads card_faces
// when present (a DFC's top-level type_line is both faces joined by " // ",
// card_faces gives each face's own line) so a transform card's back-face
// creature type still counts. Only faces whose own type line includes
// "Creature" contribute — an Instant/Sorcery/Enchantment subtype (Arcane,
// Curse, Saga...) isn't a creature type and isn't what this is for.
function creatureSubtypes(card: ScryfallCard): string[] {
  const faces = card.card_faces?.length ? card.card_faces : [card];
  const subtypes = new Set<string>();
  for (const f of faces) {
    const [main, sub] = (f.type_line || '').split('—').map((s) => s.trim());
    if (!sub || !/\bCreature\b/.test(main || '')) continue;
    for (const word of sub.split(/\s+/)) if (word) subtypes.add(word);
  }
  return [...subtypes];
}

function slugify(word: string): string {
  return word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

export function buildGraph(
  setCode: string,
  allRaw: ScryfallCard[],
  tokensById: TokensById,
  relations: RelationsEntry[],
  themes: ThemeData[]
): GraphFile {
  // Basic lands carry no synergy text and are numerous — pure clutter, drop them
  // entirely. Digital-only Alchemy rebalances aren't part of the actual paper set.
  const raw = allRaw.filter((c) => !(c.type_line || '').includes('Basic') && !c.digital);

  const curatedThemeIds = new Set(themes.map((t) => t.id));

  // slug -> display label, across every card. Skips any subtype whose slug collides
  // with an existing CURATED theme id (e.g. "dragon" already has its own richer
  // produce/consume rules as a curated theme).
  const typeThemeLabel = new Map<string, string>();
  for (const c of raw) {
    for (const word of creatureSubtypes(c)) {
      const slug = slugify(word);
      if (!slug || curatedThemeIds.has(slug)) continue;
      if (!typeThemeLabel.has(slug)) typeThemeLabel.set(slug, word);
    }
  }
  const typeThemes: ThemeData[] = [...typeThemeLabel.entries()].map(([id, label]) => ({ id, label }));
  // Union of curated + auto-generated theme ids — both are valid targets for a
  // relations entry; only the EDGE is manual for creature types, the theme id
  // itself already exists once any card's type_line produces it.
  const themeIds = new Set([...curatedThemeIds, ...typeThemeLabel.keys()]);

  const relationsByName = new Map(relations.map((t) => [t.name, t]));

  const cards: CardData[] = raw.map((c) => ({
    id: c.id,
    name: c.name,
    cmc: c.cmc ?? 0,
    colors: c.colors || (c.card_faces ? c.card_faces.flatMap((f) => f.colors || []) : []),
    colorIdentity: c.color_identity || [],
    typeLine: c.type_line || '',
    rarity: c.rarity || 'common',
    images: cardImages(c),
    tokens: cardTokens(c, tokensById),
    scryfallUri: c.scryfall_uri,
    keywords: cardKeywords(c).filter((k) => BADGE_KEYWORDS.has(k)),
  }));

  const edges: EdgeData[] = [];
  for (const c of raw) {
    const entry = relationsByName.get(c.name);
    if (!entry) {
      edges.push({ card: c.id, theme: 'not-processed', role: 'atypical', weight: 1 });
    } else {
      for (const [role, byTheme] of Object.entries(entry.themes ?? {})) {
        for (const [theme, weight] of Object.entries(byTheme ?? {})) {
          if (theme !== 'not-processed' && !themeIds.has(theme)) {
            console.warn(`"${c.name}": unknown theme id "${theme}" (not in data/global_themes.json and no card's type_line produces it) — skipping.`);
            continue;
          }
          edges.push({ card: c.id, theme, role: role as Role, weight });
        }
      }
    }
  }

  return {
    set: setCode,
    themes: [...themes, ...typeThemes, { id: 'not-processed', label: 'Not Processed' }],
    cards,
    edges,
  };
}
