// Assembles the in-memory GraphFile the main visualizer renders — cards plus
// direct card<->card synergy links — from raw pieces fetched straight from
// data/ and server/api/graph-links.ts (no pre-built graph file, no
// server-side merge step; see README for why: "graph should be generated by
// visualizer, not in advance by some server script"). Ported 1:1 from the
// old scripts/build-graph.mjs, which this replaces.
//
// Links come from functional-model's real, verified synergy matching
// (server/api/graph-links.ts), keyed by card NAME — resolved to Scryfall ids
// here, against the same corpus this function already has loaded. This
// module also still exports creatureSubtypes/slugify/RelationsEntry — the
// card detail page's own route (server/api/card/[set]/[number].ts) uses
// them for its separate, still-curated "Synergy model" theme column; only
// this file's own buildGraph() body has stopped consuming them.

import type { CardData, CardLink, GraphFile, GraphReason, Role } from '../types';

// Loosely typed — only the Scryfall fields this module actually reads.
export interface ScryfallCard {
  id: string;
  name: string;
  cmc?: number;
  colors?: string[];
  color_identity?: string[];
  type_line?: string;
  rarity?: string;
  scryfall_uri: string;
  keywords?: string[];
  digital?: boolean;
  oracle_text?: string;
  mana_cost?: string;
  power?: string;
  toughness?: string;
  flavor_text?: string;
  color_indicator?: string[];
  image_uris?: { normal: string; art_crop?: string };
  card_faces?: {
    name?: string;
    colors?: string[];
    /** A back face with no mana cost of its own (a transform DFC) prints this instead — Scryfall's own "Color Indicator: ..." line (e.g. Shiva, Warden of Ice). */
    color_indicator?: string[];
    type_line?: string;
    keywords?: string[];
    oracle_text?: string;
    mana_cost?: string;
    power?: string;
    toughness?: string;
    flavor_text?: string;
    image_uris?: { normal: string; art_crop?: string };
  }[];
  all_parts?: { id: string; component: string }[];
  set?: string;
  collector_number?: string;
  // Deck-import mode only (see server/api/cards/by-names.ts) — how many
  // copies are in the active deck. Absent in every other mode.
  qty?: number;
}

export type TokensById = Record<string, { name: string; image: string | null }>;

export interface RelationsEntry {
  name: string;
  themes: Partial<Record<Role, Record<string, number>>>;
}

// Evergreen / combat keywords -> rendered as badges on the card node, not graph edges.
export const BADGE_KEYWORDS = new Set([
  'Flying', 'Trample', 'Vigilance', 'Reach', 'Menace', 'Deathtouch', 'Haste',
  'Lifelink', 'Ward', 'Indestructible', 'Flash', 'Crew', 'First strike', 'Double strike',
  'Hexproof', 'Defender',
]);

// Single-faced (and split/adventure, which share one image at the top level) cards
// return one URL; true double-faced cards (each face has its own image_uris) return
// both, front first, so the UI can show both sides on hover.
export function cardImages(card: ScryfallCard): string[] {
  if (card.image_uris) return [card.image_uris.normal];
  return (card.card_faces || []).filter((f) => f.image_uris).map((f) => f.image_uris!.normal);
}

// Front face's art crop only (just the illustration, no frame/text) — the
// graph node's own circle-clipped art (app/lib/graphRenderer.ts) uses this,
// not cardImages()'s full card scan, which stays for the hover tooltip
// (CardMedia.vue) where the whole card is what's wanted. `null` for the rare
// card missing an art_crop URL rather than falling back to the full card —
// graphRenderer.ts already has its own flat-color fallback for that case.
export function cardArtCrop(card: ScryfallCard): string | null {
  return card.image_uris?.art_crop ?? card.card_faces?.[0]?.image_uris?.art_crop ?? null;
}

export function cardKeywords(card: ScryfallCard): string[] {
  const kws = new Set(card.keywords || []);
  for (const f of card.card_faces || []) for (const k of f.keywords || []) kws.add(k);
  return [...kws];
}

// Scryfall's own `keywords` array (cardKeywords above) only ever lists
// abilities the card itself HAS — never one it merely GRANTS or references
// on something else. FIN's Zack Fair ("{1}, Sacrifice Zack Fair: Target
// creature you control gains indestructible until end of turn...") carries
// an empty `keywords` array despite very much being "about" indestructible;
// no amount of reading that array catches it. This instead scans the card's
// own raw oracle text (all faces) for a plain, case-insensitive, whole-word
// match against each BADGE_KEYWORDS entry — deliberately not scoped to
// "grants X" phrasing specifically: a card that only REFERENCES a keyword
// ability on something else (e.g. "creatures you control with flying get
// +1/+1") is just as relevant to badge, by this feature's own design call
// (see graphRenderer.ts's keyword-icon strip, the only consumer of this).
function keywordMentions(card: ScryfallCard, badgeKeywords: Set<string>): string[] {
  const text = [card.oracle_text, ...(card.card_faces || []).map((f) => f.oracle_text)].filter(Boolean).join('\n');
  if (!text) return [];
  const found: string[] = [];
  for (const kw of badgeKeywords) {
    if (new RegExp(`\\b${kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i').test(text)) found.push(kw);
  }
  return found;
}

export function cardTokens(card: ScryfallCard, tokensById: TokensById): { name: string; image: string }[] {
  const seen = new Set<string>();
  const tokens: { name: string; image: string }[] = [];
  for (const p of card.all_parts || []) {
    if (p.component !== 'token' || seen.has(p.id)) continue;
    seen.add(p.id);
    const t = tokensById[p.id];
    if (t?.image) tokens.push({ name: t.name, image: t.image });
  }
  return tokens;
}

// "Legendary Creature — Human Knight" -> ["Human", "Knight"]. Reads card_faces
// when present (a DFC's top-level type_line is both faces joined by " // ",
// card_faces gives each face's own line) so a transform card's back-face
// creature type still counts. Only faces whose own type line includes
// "Creature" contribute — an Instant/Sorcery/Enchantment subtype (Arcane,
// Curse, Saga...) isn't a creature type and isn't what this is for.
export function creatureSubtypes(card: ScryfallCard): string[] {
  const faces = card.card_faces?.length ? card.card_faces : [card];
  const subtypes = new Set<string>();
  for (const f of faces) {
    const [main, sub] = (f.type_line || '').split('—').map((s) => s.trim());
    if (!sub || !/\bCreature\b/.test(main || '')) continue;
    for (const word of sub.split(/\s+/)) if (word) subtypes.add(word);
  }
  return [...subtypes];
}

export function slugify(word: string): string {
  return word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

// server/api/graph-links.ts's own GraphLink shape, but keyed by card NAME
// (that route has no Scryfall id to key by — functional-model deals in
// names) rather than the resolved id CardLink itself carries. Kept as a
// separate, minimal local type instead of importing the server route's own
// type, same reasoning ScryfallCard/RelationsEntry below stay hand-typed
// (loosely typed — only the fields this module actually reads).
export interface NameLink {
  a: string;
  b: string;
  reasons: GraphReason[];
}

export function buildGraph(setCode: string, allRaw: ScryfallCard[], tokensById: TokensById, links: NameLink[]): GraphFile {
  // Basic lands carry no synergy text and are numerous — pure clutter across a
  // whole set, drop them entirely there. A real decklist is a different case:
  // its basics are actual deck content the user just pasted in (and, with the
  // qty merge, exactly where a "×17 Island" badge is most worth seeing) — not
  // clutter at that scale, so deck mode keeps them. Digital-only Alchemy
  // rebalances still never belong (not part of the actual paper set, deck
  // mode or not — a decklist naming one is a name collision with a real card,
  // not an intentional pick).
  const raw = allRaw.filter((c) => (setCode === 'deck' || !(c.type_line || '').includes('Basic')) && !c.digital);

  const idByName = new Map(raw.map((c) => [c.name, c.id]));

  const cards: CardData[] = raw.map((c) => ({
    id: c.id,
    name: c.name,
    cmc: c.cmc ?? 0,
    // Front face's own cost FIRST, top-level `mana_cost` only as a fallback
    // for a genuinely single-faced card (no `card_faces` at all) — the
    // reverse priority looked equivalent for a transform/modal_dfc card
    // (Scryfall leaves the top-level field blank there, so it always fell
    // through to card_faces[0] anyway) but silently broke for split/
    // adventure/flip layouts: Scryfall's top-level `mana_cost` for THOSE is
    // every face's own cost joined by " // " as one literal string (e.g.
    // "{2}{G/U}{G/U} // {1}{G/U}{G/U}" for an adventure card) — confirmed
    // concretely via a live `?sf=` query surfacing "Thranduil, Sindarin
    // Liege // Silvan Rally" (HOB), whose node showed BOTH faces' pips
    // concatenated in one title bar (6 pips: 2, G/U, G/U, 1, G/U, G/U) since
    // manaPipCodes()/parseManaSegments() below just extracts every `{...}`
    // chunk in the string, oblivious to the " // " separator in between.
    // card_faces[0].mana_cost is always just the single front/primary
    // face's own cost, correct across every layout this corpus can see.
    manaCost: c.card_faces?.[0]?.mana_cost ?? c.mana_cost ?? null,
    colors: c.colors || (c.card_faces ? c.card_faces.flatMap((f) => f.colors || []) : []),
    colorIdentity: c.color_identity || [],
    typeLine: c.type_line || '',
    rarity: c.rarity || 'common',
    images: cardImages(c),
    artCrop: cardArtCrop(c),
    tokens: cardTokens(c, tokensById),
    scryfallUri: c.scryfall_uri,
    keywords: [...new Set([...cardKeywords(c).filter((k) => BADGE_KEYWORDS.has(k)), ...keywordMentions(c, BADGE_KEYWORDS)])],
    set: c.set || '',
    collectorNumber: c.collector_number || '',
    qty: c.qty,
  }));

  // A link whose name doesn't resolve (basic land / digital card filtered out
  // above, or a functional-model card this corpus doesn't have — e.g. a BLB
  // card in query mode) is dropped rather than rendered dangling.
  const resolvedLinks: CardLink[] = [];
  for (const l of links) {
    const a = idByName.get(l.a);
    const b = idByName.get(l.b);
    if (!a || !b) continue;
    resolvedLinks.push({ a, b, reasons: l.reasons });
  }

  return {
    set: setCode,
    cards,
    links: resolvedLinks,
  };
}
