// Assembles the in-memory GraphFile the main visualizer renders — cards plus
// direct card<->card synergy links — from raw pieces fetched straight from
// data/ and server/api/graph-links.ts (no pre-built graph file, no
// server-side merge step; see README for why: "graph should be generated by
// visualizer, not in advance by some server script"). Ported 1:1 from the
// old scripts/build-graph.mjs, which this replaces.
//
// Links come from functional-model's real, verified synergy matching
// (server/api/graph-links.ts), keyed by card NAME — resolved to Scryfall ids
// here, against the same corpus this function already has loaded. This
// module also still exports creatureSubtypes/slugify/RelationsEntry — the
// card detail page's own route (server/api/card/[set]/[number].ts) uses
// them for its separate, still-curated "Synergy model" theme column; only
// this file's own buildGraph() body has stopped consuming them.

import type { CardData, CardLink, GraphFile, GraphReason, Role } from '../types';

// Loosely typed — only the Scryfall fields this module actually reads.
export interface ScryfallCard {
  id: string;
  name: string;
  cmc?: number;
  colors?: string[];
  color_identity?: string[];
  type_line?: string;
  rarity?: string;
  scryfall_uri: string;
  keywords?: string[];
  digital?: boolean;
  oracle_text?: string;
  mana_cost?: string;
  power?: string;
  toughness?: string;
  flavor_text?: string;
  color_indicator?: string[];
  image_uris?: { normal: string; art_crop?: string };
  card_faces?: {
    name?: string;
    colors?: string[];
    /** A back face with no mana cost of its own (a transform DFC) prints this instead — Scryfall's own "Color Indicator: ..." line (e.g. Shiva, Warden of Ice). */
    color_indicator?: string[];
    type_line?: string;
    keywords?: string[];
    oracle_text?: string;
    mana_cost?: string;
    power?: string;
    toughness?: string;
    flavor_text?: string;
    image_uris?: { normal: string; art_crop?: string };
  }[];
  all_parts?: { id: string; component: string }[];
  set?: string;
  collector_number?: string;
  // ISO date ("YYYY-MM-DD") of this specific printing — present on the raw
  // static per-set JSON (fetched directly, no server reshaping) and on
  // server/api/cards.ts's own response (its `minimalCard()` currently drops
  // it before this ever hits the client for THAT route — see CardData's own
  // `releasedAt` comment); declared here regardless so a future passthrough
  // fix on that route needs no change on this side.
  released_at?: string;
}

export type TokensById = Record<string, { name: string; image: string | null }>;

export interface RelationsEntry {
  name: string;
  themes: Partial<Record<Role, Record<string, number>>>;
}

// Evergreen / combat keywords -> rendered as badges on the card node, not graph edges.
export const BADGE_KEYWORDS = new Set([
  'Flying', 'Trample', 'Vigilance', 'Reach', 'Menace', 'Deathtouch', 'Haste',
  'Lifelink', 'Ward', 'Indestructible', 'Flash', 'Crew', 'First strike', 'Double strike',
  'Hexproof', 'Defender',
]);

// Single-faced (and split/adventure, which share one image at the top level) cards
// return one URL; true double-faced cards (each face has its own image_uris) return
// both, front first, so the UI can show both sides on hover.
export function cardImages(card: ScryfallCard): string[] {
  if (card.image_uris) return [card.image_uris.normal];
  return (card.card_faces || []).filter((f) => f.image_uris).map((f) => f.image_uris!.normal);
}

// Front face's art crop only (just the illustration, no frame/text) — the
// graph node's own circle-clipped art (app/lib/graphRenderer.ts) uses this,
// not cardImages()'s full card scan, which stays for the hover tooltip
// (CardMedia.vue) where the whole card is what's wanted. `null` for the rare
// card missing an art_crop URL rather than falling back to the full card —
// graphRenderer.ts already has its own flat-color fallback for that case.
export function cardArtCrop(card: ScryfallCard): string | null {
  return card.image_uris?.art_crop ?? card.card_faces?.[0]?.image_uris?.art_crop ?? null;
}

export function cardKeywords(card: ScryfallCard): string[] {
  const kws = new Set(card.keywords || []);
  for (const f of card.card_faces || []) for (const k of f.keywords || []) kws.add(k);
  return [...kws];
}

// Face-scoped keywords — unlike `cardKeywords` above (deliberately a union
// across every face, for the graph node's own single "this card has these
// abilities somewhere" badge strip), a transform DFC's two faces can have
// genuinely DIFFERENT printed keywords (e.g. FIN's Crystal Fragments //
// Summon: Alexander — front face has no Flying, only the back Summon:
// Alexander face does). Scryfall's own top-level `card.keywords` is already
// the union of both, so reading it directly for a specific face is wrong —
// but Scryfall ALSO doesn't serve a per-face `keywords` array at all
// (confirmed live against the real `/cards/<set>/<num>` API for several FIN
// transform DFCs: every `card_faces[i]` entry omits the field entirely, only
// the whole-card top-level array exists). So this scans this face's own
// `oracle_text` for a standalone keyword line instead — the MTG frame
// convention a printed keyword ability always follows (its own line, comma-
// separated if more than one, optionally with a trailing cost/number like
// "Ward {2}"), restricted to keywords `card.keywords` already confirms this
// card genuinely HAS somewhere (never a mention/grant the whole-card field
// itself already excludes — see `keywordMentions` below for that
// distinction). This is what correctly tells apart Dion, Bahamut's
// Dominant's front face — which only MENTIONS "flying" inside a full
// sentence ("Dragonfire Dive — During your turn, Dion and other Knights you
// control have flying," a CONTINUOUS, turn-conditional grant — handled
// separately by `CardDefinition.continuousKeywordGrants`/
// `ScenarioReplayTrace.vue`'s own `continuousGrantedKeywords`, not a static
// printed keyword this function should ever report) — from its back face
// Bahamut, Warden of Light, which prints "Flying" as its own bare line
// (Bahamut's own real, unconditional keyword). Used by the card-detail page,
// which always knows which face
// it's showing (front/back toggle, or a scenario replay mid-transform) and
// must not badge a not-yet-transformed front face with a keyword only the
// back face has, or vice versa. A card with no `card_faces` (single-faced,
// split, adventure — sharing one face) has only "face 0", the whole card's
// own `keywords` untouched (no per-face ambiguity to resolve there).
export function cardFaceKeywords(card: ScryfallCard, face: number): string[] {
  const whole = card.keywords || [];
  if (!card.card_faces?.length || !whole.length) return face === 0 ? whole : [];
  const text = card.card_faces[face]?.oracle_text ?? '';
  const found = new Set<string>();
  for (const rawLine of text.split('\n')) {
    // Reminder text often trails the keyword on the SAME line, no comma
    // separator ("Crew 1 (Tap any number of creatures...)", "Menace (This
    // creature can't be blocked except by two or more creatures.)") — strip
    // it before splitting on comma, or it'd swallow the whole line as one
    // non-matching segment.
    const line = rawLine.replace(/\([^)]*\)/g, '');
    for (const seg of line.split(',')) {
      // Strip a trailing reminder-cost/number ("Ward {2}", "Crew 2") and any
      // trailing sentence punctuation before the exact-match check below.
      const bare = seg.trim().replace(/[.:]$/, '').replace(/\s*(\{[^}]*\}|\d+)\s*$/, '').trim();
      const match = whole.find((k) => k.toLowerCase() === bare.toLowerCase());
      if (match) found.add(match);
    }
  }
  return [...found];
}

// Scryfall's own `keywords` array (cardKeywords above) only ever lists
// abilities the card itself HAS — never one it merely GRANTS or references
// on something else. FIN's Zack Fair ("{1}, Sacrifice Zack Fair: Target
// creature you control gains indestructible until end of turn...") carries
// an empty `keywords` array despite very much being "about" indestructible;
// no amount of reading that array catches it. This instead scans the card's
// own raw oracle text (all faces) for a plain, case-insensitive, whole-word
// match against each BADGE_KEYWORDS entry — deliberately not scoped to
// "grants X" phrasing specifically: a card that only REFERENCES a keyword
// ability on something else (e.g. "creatures you control with flying get
// +1/+1") is just as relevant to badge, by this feature's own design call
// (see graphRenderer.ts's keyword-icon strip, the only consumer of this).
function keywordMentions(card: ScryfallCard, badgeKeywords: Set<string>): string[] {
  const text = [card.oracle_text, ...(card.card_faces || []).map((f) => f.oracle_text)].filter(Boolean).join('\n');
  if (!text) return [];
  const found: string[] = [];
  for (const kw of badgeKeywords) {
    if (new RegExp(`\\b${kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i').test(text)) found.push(kw);
  }
  return found;
}

export function cardTokens(card: ScryfallCard, tokensById: TokensById): { name: string; image: string }[] {
  const seen = new Set<string>();
  const tokens: { name: string; image: string }[] = [];
  for (const p of card.all_parts || []) {
    if (p.component !== 'token' || seen.has(p.id)) continue;
    seen.add(p.id);
    const t = tokensById[p.id];
    if (t?.image) tokens.push({ name: t.name, image: t.image });
  }
  return tokens;
}

// "Legendary Creature — Human Knight" -> ["Human", "Knight"]. Reads card_faces
// when present (a DFC's top-level type_line is both faces joined by " // ",
// card_faces gives each face's own line) so a transform card's back-face
// creature type still counts. Only faces whose own type line includes
// "Creature" contribute — an Instant/Sorcery/Enchantment subtype (Arcane,
// Curse, Saga...) isn't a creature type and isn't what this is for.
export function creatureSubtypes(card: ScryfallCard): string[] {
  const faces = card.card_faces?.length ? card.card_faces : [card];
  const subtypes = new Set<string>();
  for (const f of faces) {
    const [main, sub] = (f.type_line || '').split('—').map((s) => s.trim());
    if (!sub || !/\bCreature\b/.test(main || '')) continue;
    for (const word of sub.split(/\s+/)) if (word) subtypes.add(word);
  }
  return [...subtypes];
}

export function slugify(word: string): string {
  return word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

// server/api/graph-links.ts's own GraphLink shape, but keyed by card NAME
// (that route has no Scryfall id to key by — functional-model deals in
// names) rather than the resolved id CardLink itself carries. Kept as a
// separate, minimal local type instead of importing the server route's own
// type, same reasoning ScryfallCard/RelationsEntry below stay hand-typed
// (loosely typed — only the fields this module actually reads).
export interface NameLink {
  a: string;
  b: string;
  reasons: GraphReason[];
}

// One card's own raw Scryfall JSON -> this app's CardData shape. Extracted
// out of buildGraph()'s own per-card map (which still just calls this, with
// its own tokensById in hand) so the same mapping is available to a single
// bulk-resolved card outside a whole-corpus load too — see
// useGraphStore.ts's `importDeckFromText` (bulk deck-paste import, resolves
// several cards at once via `/api/cards/by-names`, which returns this same
// raw ScryfallCard shape, not already-built CardData the way the single-
// card `/api/card/[set]/[number]` route does). `tokensById` defaults to `{}`
// for a caller with no token-image map in hand (that bulk-import path never
// fetches one, same as the old deck-import branch this replaces never did
// either) — just means no token hover art for that card, not a broken card.
export function scryfallCardToCardData(c: ScryfallCard, tokensById: TokensById = {}): CardData {
  return {
    id: c.id,
    name: c.name,
    cmc: c.cmc ?? 0,
    // Front face's own cost FIRST, top-level `mana_cost` only as a fallback
    // for a genuinely single-faced card (no `card_faces` at all) — the
    // reverse priority looked equivalent for a transform/modal_dfc card
    // (Scryfall leaves the top-level field blank there, so it always fell
    // through to card_faces[0] anyway) but silently broke for split/
    // adventure/flip layouts: Scryfall's top-level `mana_cost` for THOSE is
    // every face's own cost joined by " // " as one literal string (e.g.
    // "{2}{G/U}{G/U} // {1}{G/U}{G/U}" for an adventure card) — confirmed
    // concretely via a live `?sf=` query surfacing "Thranduil, Sindarin
    // Liege // Silvan Rally" (HOB), whose node showed BOTH faces' pips
    // concatenated in one title bar (6 pips: 2, G/U, G/U, 1, G/U, G/U) since
    // manaPipCodes()/parseManaSegments() below just extracts every `{...}`
    // chunk in the string, oblivious to the " // " separator in between.
    // card_faces[0].mana_cost is always just the single front/primary
    // face's own cost, correct across every layout this corpus can see.
    manaCost: c.card_faces?.[0]?.mana_cost ?? c.mana_cost ?? null,
    colors: c.colors || (c.card_faces ? c.card_faces.flatMap((f) => f.colors || []) : []),
    colorIdentity: c.color_identity || [],
    typeLine: c.type_line || '',
    rarity: c.rarity || 'common',
    images: cardImages(c),
    artCrop: cardArtCrop(c),
    tokens: cardTokens(c, tokensById),
    scryfallUri: c.scryfall_uri,
    keywords: [...new Set([...cardKeywords(c).filter((k) => BADGE_KEYWORDS.has(k)), ...keywordMentions(c, BADGE_KEYWORDS)])],
    set: c.set || '',
    collectorNumber: c.collector_number || '',
    releasedAt: c.released_at,
  };
}

// Resolves a whole-pool NameLink[] (keyed by card name — functional-model's
// own vocabulary, see NameLink's own comment) down to the CardLink[] a
// GraphFile actually carries, against whichever cards[] are in hand right
// now. Extracted out of buildGraph() so useGraphStore.ts's own Scope∪Deck
// union (PRD 01 "Core concepts") can re-resolve links against the CURRENT
// effective card set — which includes individually added Scope cards and
// Deck entries buildGraph() itself never sees — using the SAME whole-pool
// NameLink[] retained from the one `/api/graph-links` fetch, rather than
// duplicating this resolution logic. A link whose name doesn't resolve
// (dropped from cards[] entirely, or a functional-model card this corpus
// doesn't have at all — e.g. a BLB card in query mode) is dropped rather
// than rendered dangling.
export function resolveCardLinks(cards: { id: string; name: string }[], links: NameLink[]): CardLink[] {
  const idByName = new Map(cards.map((c) => [c.name, c.id]));
  const resolved: CardLink[] = [];
  for (const l of links) {
    const a = idByName.get(l.a);
    const b = idByName.get(l.b);
    if (!a || !b) continue;
    resolved.push({ a, b, reasons: l.reasons });
  }
  return resolved;
}

export function buildGraph(setCode: string, allRaw: ScryfallCard[], tokensById: TokensById, links: NameLink[]): GraphFile {
  // Basic lands carry no synergy text and are numerous — pure clutter across
  // a whole bulk-loaded set, drop them entirely there. A Deck/Scope card
  // added individually (useGraphStore.ts's own addCardToScope/addCardToDeck/
  // importDeckFromText) bypasses this filter by construction — it's never
  // built via this function at all, so a genuinely-wanted basic land added
  // one-by-one, or a deck's own "×17 Island," is never at risk of being
  // silently dropped the way it would be if it came in through THIS bulk
  // path. Digital-only Alchemy rebalances never belong here either way (not
  // part of the actual paper set).
  const raw = allRaw.filter((c) => !(c.type_line || '').includes('Basic') && !c.digital);

  const cards: CardData[] = raw.map((c) => scryfallCardToCardData(c, tokensById));

  return {
    set: setCode,
    cards,
    links: resolveCardLinks(cards, links),
  };
}
