// Keyword/mechanic coverage suite registry — drives the "Keywords" page
// (app/pages/app/keywords/index.vue) and the server route that serves it
// (server/api/keywords/index.get.ts). Each `covered` entry names a real
// engine-piloted bundle under functional-model/keywords/<bundle>/
// (scenarios.ts + trace.json, generated by
// functional-model/scripts/run-keyword-scenarios.mjs) proving the engine
// genuinely implements that keyword/mechanic — real cards, no mocks, same
// discipline as functional-model/cards/<slug>. A `gap` entry has no
// scenario at all: the keyword is recognized (card.ts's own `Keyword`
// union) but nothing in engine.ts/state.ts/sba.ts actually enforces it, so
// there is nothing real to demonstrate yet — listed anyway so the page is
// an honest, complete picture of coverage, not just of successes.
//
// NOT scanned by functional-model/scripts/verify-synergy.mjs or
// run-scenarios.mjs (both only ever walk functional-model/cards/) — this
// tree is entirely additive, no synergy.json of its own, no interaction
// with the per-card fact-matching pipeline.
//
// Follow-up (not built yet, flagged for the next pass): once a keyword's
// own bundle here is trusted, the "apply this proof to every card that
// carries the keyword" step would mean each `functional-model/cards/<slug>`
// with e.g. `keywords: ['Flying']` gets that fact attached automatically
// (a `sourceText`/`id` referencing this registry's own `key`, surfaced in
// its synergy.json some way) instead of every plain-vanilla-keyword card
// needing its own bespoke scenario — this file's `key`/`keywords` fields
// are shaped so a future script can look up "which registry entry covers
// keyword X" directly off `keywords`, but no such script exists yet.

export type KeywordStatus = 'covered' | 'gap';

export interface KeywordEntry {
  /** Stable id — used as this entry's own page anchor/URL slug. */
  key: string;
  /** Directory name under functional-model/keywords/ — undefined for a `gap` entry (nothing to run). */
  bundle?: string;
  title: string;
  /** Real `Keyword` union members (card.ts) this entry covers/discusses. */
  keywords: string[];
  /** Comprehensive Rules citation(s) this entry's own scenario/gap note is checked against. */
  ruleCite: string;
  /** Real card name(s) (Scryfall's own `name`) this entry demonstrates with. Empty for a `gap` entry with no real FIN/pool card carrying the keyword at all. */
  cardNames: string[];
  category: 'evergreen' | 'fin-mechanic';
  status: KeywordStatus;
  /** Required for a `gap` entry — why there's no scenario. */
  gapNote?: string;
}

export const KEYWORD_REGISTRY: KeywordEntry[] = [
  {
    key: 'flying-reach',
    bundle: 'flying-reach',
    title: 'Flying & Reach',
    keywords: ['Flying', 'Reach'],
    ruleCite: '509.1b',
    cardNames: ['Ahriman', 'Iron Giant'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'vigilance-trample',
    bundle: 'vigilance-trample',
    title: 'Vigilance & Trample',
    keywords: ['Vigilance', 'Trample'],
    ruleCite: '508.1f / 702.19c',
    cardNames: ['Iron Giant'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'menace',
    bundle: 'menace',
    title: 'Menace',
    keywords: ['Menace'],
    ruleCite: '509.1b / 702.111b',
    cardNames: ['Xande, Dark Mage'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'deathtouch',
    bundle: 'deathtouch',
    title: 'Deathtouch',
    keywords: ['Deathtouch'],
    ruleCite: '702.2e / 704.5h',
    cardNames: ['Gran Pulse Ochu'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'first-strike-double-strike',
    bundle: 'first-strike-double-strike',
    title: 'First Strike & Double Strike',
    keywords: ['FirstStrike', 'DoubleStrike'],
    ruleCite: '510.5',
    cardNames: ['Lightning, Army of One', 'Giott, King of the Dwarves'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'lifelink',
    bundle: 'lifelink',
    title: 'Lifelink',
    keywords: ['Lifelink'],
    ruleCite: '702.15e',
    cardNames: ['Adelbert Steiner'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'indestructible',
    bundle: 'indestructible',
    title: 'Indestructible',
    keywords: ['Indestructible'],
    ruleCite: '702.12b / 704.5f',
    cardNames: ['Zodiark, Umbral God'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'haste',
    bundle: 'haste',
    title: 'Haste',
    keywords: ['Haste'],
    ruleCite: '302.6',
    cardNames: ['Prompto Argentum'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'flash',
    bundle: 'flash',
    title: 'Flash',
    keywords: ['Flash'],
    ruleCite: '307.1a / 117.1a',
    cardNames: ['Ambrosia Whiteheart', 'Gran Pulse Ochu'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'defender',
    bundle: 'defender',
    title: 'Defender',
    keywords: ['Defender'],
    ruleCite: '302.6a',
    cardNames: ['Demon Wall'],
    category: 'evergreen',
    status: 'covered',
  },
  {
    key: 'hexproof',
    title: 'Hexproof',
    keywords: ['Hexproof'],
    ruleCite: '702.11b',
    cardNames: [],
    category: 'evergreen',
    status: 'gap',
    gapNote:
      'Recognized only as a Keyword string-union member (card.ts) — no targeting-legality machinery exists anywhere in engine.ts/card.ts to enforce it (there is no pre-resolution "declare and validate targets" step at all, a documented gap — see engine.ts\'s own header). No real card in this pool (all 312 are FIN) carries Hexproof either.',
  },
  {
    key: 'ward',
    title: 'Ward',
    keywords: ['Ward'],
    ruleCite: '702.21e',
    cardNames: ['Raubahn, Bull of Ala Mhigo', 'Ancient Adamantoise', 'Summon: Leviathan'],
    category: 'evergreen',
    status: 'gap',
    gapNote:
      'Recognized only as a Keyword string-union member (card.ts) — same missing targeting-legality/triggered-cost machinery as Hexproof. 3 real FIN cards carry Ward, but nothing in the engine enforces or triggers it yet.',
  },
  {
    key: 'protection',
    title: 'Protection',
    keywords: ['Protection'],
    ruleCite: '702.16',
    cardNames: [],
    category: 'evergreen',
    status: 'gap',
    gapNote:
      "Not even in card.ts's own Keyword union yet, and no real card in this pool (all 312 are FIN) carries Protection — nothing to build against.",
  },
  {
    key: 'saga',
    bundle: 'saga',
    title: 'Saga chapters',
    keywords: ['Saga'],
    ruleCite: '714.2b/c, 714.3a/b, 714.4',
    cardNames: ['Summon: Knights of Round'],
    category: 'fin-mechanic',
    status: 'covered',
  },
  {
    key: 'landfall',
    bundle: 'landfall',
    title: 'Landfall',
    keywords: ['Landfall'],
    ruleCite: '(FIN reminder text — not a Comprehensive Rules keyword of its own; modeled as a plain named trigger, see engine.ts/card.ts)',
    cardNames: ['Ambrosia Whiteheart'],
    category: 'fin-mechanic',
    status: 'covered',
  },
];
