// Azure Beastbinder
// Scryfall: blb #41 — Creature — Rat Rogue
// Vigilance
// This creature can't be blocked by creatures with power 2 or greater.
// Whenever this creature attacks, up to one target artifact, creature, or planeswalker an opponent controls loses all abilities until your next turn. If it's a creature, it also has base power and toughness 2/2 until your next turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/azure-beastbinder.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Azure Beastbinder
// {1}{U}  Creature Rat Rogue  1/3

// Keyword: Vigilance — doesn't tap to attack

/** Static: this can't be blocked by creature (continuous). Continuous, not event-driven — no real executable body. */
export function staticEffect(self: Card, you: Player, opp: Player[]): void {
  // this can't be blocked by creature (continuous)
}

/**
 * Trigger: when this attacks.
 */
export function onAttacks(self: Card, you: Player, opp: Player[]): void {
  // unmapped: Animate(ValidTgts=Artifact.OppCtrl,Creature.OppCtrl,Planeswalker.OppCtrl, TgtPrompt=Select up to one target artifact, creature, or planeswalker an opponent controls, TargetMin=0, TargetMax=1, RemoveAllAbilities=True, Duration=UntilYourNextTurn)
  // unmapped: Animate(Defined=Targeted.Creature, Power=2, Toughness=2, Duration=UntilYourNextTurn)
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Azure Beastbinder: effect "Animate" has no real-code builder yet
//   - Azure Beastbinder: effect "Animate" has no real-code builder yet
