// Banishing Light
// Scryfall: blb #1 — Enchantment
// When this enchantment enters, exile target nonland permanent an opponent controls until this enchantment leaves the battlefield.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/banishing-light.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Banishing Light
// {2}{W}  Enchantment

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(opp[0].getCardsIn('Battlefield')), 'Exile');  // Duration=UntilHostLeavesPlay
}
