// Bellowing Crier
// Scryfall: blb #42 — Creature — Frog Advisor
// When this creature enters, draw a card, then discard a card.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/bellowing-crier.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Bellowing Crier
// {1}{U}  Creature Frog Advisor  2/1

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  you.drawCard();
  discard(you, 1);
}
