// Beza, the Bounding Spring
// Scryfall: blb #2 — Legendary Creature — Elemental Elk
// When Beza enters, create a Treasure token if an opponent controls more lands than you. You gain 4 life if an opponent has more life than you. Create two 1/1 blue Fish creature tokens if an opponent controls more creatures than you. Draw a card if an opponent has more cards in hand than you.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/beza-the-bounding-spring.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Beza, the Bounding Spring
// {2}{W}{W}  Legendary Creature Elemental Elk  4/5

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  if (highest(opp, (p) => p.getLandsInPlay().length) > you.getLandsInPlay().length) {
    createToken(you, TOKENS.c_a_treasure_sac);
  }
  if (highest(opp, (p) => p.getLife()) > you.getLife()) {
    you.gainLife(4, self);
  }
  if (highest(opp, (p) => p.getCreaturesInPlay().length) > you.getCreaturesInPlay().length) {
    createToken(you, TOKENS.u_1_1_fish, 2);
  }
  if (highest(opp, (p) => p.getCardsIn('Hand').length) > you.getCardsIn('Hand').length) {
    you.drawCard();
  }
}
