// Brave-Kin Duo
// Scryfall: blb #3 — Creature — Rabbit Mouse
// {1}, {T}: Target creature gets +1/+1 until end of turn. Activate only as a sorcery.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/brave-kin-duo.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Brave-Kin Duo
// {W}  Creature Rabbit Mouse  1/1

/** Cost: {1}, {T}. */
export function activated(self: Card, you: Player, opp: Player[]): void {
  pump(chooseTarget(you.getCreaturesInPlay()), +1, +1);  // SorcerySpeed=True
}
