// Brightblade Stoat
// Scryfall: blb #4 — Creature — Weasel Soldier
// First strike, lifelink
// Generated by app/lib/functionalTranslate.ts from forge-model/data/brightblade-stoat.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Brightblade Stoat
// {1}{W}  Creature Weasel Soldier  2/2

// Keyword: First Strike — deals combat damage before creatures without it

// Keyword: Lifelink — damage dealt also gains you that much life
