// Builder's Talent
// Scryfall: blb #5 — Enchantment — Class
// (Gain the next level as a sorcery to add its ability.)
// When this Class enters, create a 0/4 white Wall creature token with defender.
// {W}: Level 2
// Whenever one or more noncreature, nonland permanents you control enter, put a +1/+1 counter on target creature you control.
// {4}{W}: Level 3
// When this Class becomes level 3, return target noncreature, nonland permanent card from your graveyard to the battlefield.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/builder-s-talent.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Builder's Talent
// {1}{W}  Enchantment Class

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  createToken(you, TOKENS.w_0_4_wall_defender);
}

/** Cost: {W}. */
export function levelUp2(self: Card, you: Player, opp: Player[]): void {
  // grants: onEnter2(...) — see below
}

/** Cost: {4}{W}. */
export function levelUp3(self: Card, you: Player, opp: Player[]): void {
  // grants: onClassLevelGained(...) — see below
}

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter2(self: Card, you: Player, opp: Player[]): void {
  putCounter(chooseTarget(you.getCreaturesInPlay()), 'P1P1', 1);
}

/**
 * Trigger: when this Class becomes level 3.
 */
export function onClassLevelGained(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(you.getCardsIn('Battlefield')), 'Battlefield');
}
