// Calamitous Tide
// Scryfall: blb #43 — Sorcery
// Return up to two target creatures to their owners' hands. Draw two cards, then discard a card.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/calamitous-tide.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Calamitous Tide
// {4}{U}{U}  Sorcery

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(you.getCreaturesInPlay()), 'Hand');  // TargetMin=0, TargetMax=2
  you.drawCards(2);
  discard(you, 1);
}
