// Caretaker's Talent
// Scryfall: blb #6 — Enchantment — Class
// (Gain the next level as a sorcery to add its ability.)
// Whenever one or more tokens you control enter, draw a card. This ability triggers only once each turn.
// {W}: Level 2
// When this Class becomes level 2, create a token that's a copy of target token you control.
// {3}{W}: Level 3
// Creature tokens you control get +2/+2.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/caretaker-s-talent.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Caretaker's Talent
// {2}{W}  Enchantment Class

/**
 * Trigger: when this enters the battlefield.
 * Only once per turn.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  you.drawCard();
}

/** Cost: {W}. */
export function levelUp2(self: Card, you: Player, opp: Player[]): void {
  // grants: onClassLevelGained(...) — see below
}

/** Cost: {3}{W}. */
export function levelUp3(self: Card, you: Player, opp: Player[]): void {
  // grants: staticEffect(...) — see below
}

/**
 * Trigger: when this Class becomes level 2.
 */
export function onClassLevelGained(self: Card, you: Player, opp: Player[]): void {
  copyPermanent(chooseTarget(you.getCardsIn('Battlefield')), you);
}

/** Static: creature gets +2/+2 (continuous). Continuous, not event-driven — no real executable body. */
export function staticEffect(self: Card, you: Player, opp: Player[]): void {
  // creature gets +2/+2 (continuous)
}
