// Carrot Cake
// Scryfall: blb #7 — Artifact — Food
// When this artifact enters and when you sacrifice it, create a 1/1 white Rabbit creature token and scry 1. (Look at the top card of your library. You may put that card on the bottom.)
// {2}, {T}, Sacrifice this artifact: You gain 3 life.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/carrot-cake.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Carrot Cake
// {1}{W}  Artifact Food

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  createToken(you, TOKENS.w_1_1_rabbit);
  scry(you, 1);  // ScryNum=1
}

/**
 * Trigger: when this is sacrificed.
 */
export function onSacrificed(self: Card, you: Player, opp: Player[]): void {
  createToken(you, TOKENS.w_1_1_rabbit);
  scry(you, 1);  // ScryNum=1
}

/** Cost: {2}, {T}, sacrifice a self. */
export function activated(self: Card, you: Player, opp: Player[]): void {
  you.gainLife(3, self);
}
