// Crumb and Get It
// Scryfall: blb #8 — Instant
// Gift a Food (You may promise an opponent a gift as you cast this spell. If you do, they create a Food token before its other effects. It's an artifact with "{2}, {T}, Sacrifice this token: You gain 3 life.")
// Target creature you control gets +2/+2 until end of turn. If the gift was promised, that creature also gains indestructible until end of turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/crumb-and-get-it.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Crumb and Get It
// {W}  Instant

/** You may promise this to an opponent as an additional cost as you cast this. */
export function gift(self: Card, you: Player, opp: Player[]): void {
  createToken(opp[0], TOKENS.c_a_food_sac);  // GiftDescription=a Food
}

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  pump(chooseTarget(you.getCreaturesInPlay()), +2, +2);
  if (false /* unmapped: the gift was promised */) {
    pump(self /* unmapped: Defined$Targeted — not tracked, using self as a type-safe placeholder */, 0, 0);  // KW=Indestructible, ConditionZone=Stack
  }
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Crumb and Get It: gift-promised condition (gift_promised) has no gift-state representation in functional-model/interfaces.ts
//   - Crumb and Get It: Defined$Targeted refers to a previously chosen/remembered card, not tracked by this translator
