// Daring Waverider
// Scryfall: blb #44 — Creature — Otter Wizard
// When this creature enters, you may cast target instant or sorcery card with mana value 4 or less from your graveyard without paying its mana cost. If that spell would be put into your graveyard, exile it instead.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/daring-waverider.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Daring Waverider
// {4}{U}{U}  Creature Otter Wizard  4/4

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  play(you, chooseTarget(you.getCardsIn('Battlefield')));  // TgtZone=Graveyard, ValidSA=Spell, WithoutManaCost=True, Optional=True, ReplaceGraveyard=Exile, AILogic=ReplaySpell
}
