// Dawn's Truce
// Scryfall: blb #9 — Instant
// Gift a card (You may promise an opponent a gift as you cast this spell. If you do, they draw a card before its other effects.)
// You and permanents you control gain hexproof until end of turn. If the gift was promised, permanents you control also gain indestructible until end of turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/dawn-s-truce.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Dawn's Truce
// {1}{W}  Instant

/** You may promise this to an opponent as an additional cost as you cast this. */
export function gift(self: Card, you: Player, opp: Player[]): void {
  opp[0].drawCard();  // GiftDescription=a card
}

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  pump(self /* unmapped: Defined$You & Valid Permanent.YouCtrl — not tracked, using self as a type-safe placeholder */, 0, 0);  // KW=Hexproof
  if (false /* unmapped: the gift was promised */) {
    for (const c of you.getCardsIn('Battlefield')) {
      pump(c, 0, 0);
    }  // KW=Indestructible, ConditionZone=Stack
  }
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Dawn's Truce: Defined$You & Valid Permanent.YouCtrl refers to a previously chosen/remembered card, not tracked by this translator
//   - Dawn's Truce: gift-promised condition (gift_promised) has no gift-state representation in functional-model/interfaces.ts
