// Dewdrop Cure
// Scryfall: blb #10 — Sorcery
// Gift a card (You may promise an opponent a gift as you cast this spell. If you do, they draw a card before its other effects.)
// Return up to two target creature cards each with mana value 2 or less from your graveyard to the battlefield. If the gift was promised, instead return up to three target creature cards each with mana value 2 or less from your graveyard to the battlefield.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/dewdrop-cure.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Dewdrop Cure
// {2}{W}  Sorcery

/** You may promise this to an opponent as an additional cost as you cast this. */
export function gift(self: Card, you: Player, opp: Player[]): void {
  opp[0].drawCard();  // GiftDescription=a card
}

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(you.getCreaturesInPlay()), 'Battlefield');  // TargetMin=0, TargetMax=X
}
