// Dire Downdraft
// Scryfall: blb #46 — Instant
// This spell costs {1} less to cast if it targets an attacking or tapped creature.
// Target creature's owner puts it on their choice of the top or bottom of their library.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/dire-downdraft.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Dire Downdraft
// {3}{U}  Instant

/** Static: costs 1 less to cast if it targets Creature.attacking,Creature.tapped (continuous). Continuous, not event-driven — no real executable body. */
export function staticEffect(self: Card, you: Player, opp: Player[]): void {
  // costs 1 less to cast if it targets Creature.attacking,Creature.tapped (continuous)
}

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(you.getCreaturesInPlay()), 'Library');  // AlternativeDecider=TargetedOwner, DestinationAlternative=Library, LibraryPositionAlternative=-1
}
