// Dour Port-Mage
// Scryfall: blb #47 — Creature — Frog Wizard
// Whenever one or more other creatures you control leave the battlefield without dying, draw a card.
// {1}{U}, {T}: Return another target creature you control to its owner's hand.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/dour-port-mage.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Dour Port-Mage
// {1}{U}  Creature Frog Wizard  1/3

/**
 * Trigger: when this leaves the battlefield without dying.
 */
export function onLeavesWithoutDying(self: Card, you: Player, opp: Player[]): void {
  you.drawCard();
}

/** Cost: {1}{U}, {T}. */
export function activated(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(you.getCreaturesInPlay()), 'Hand');
}
