// Driftgloom Coyote
// Scryfall: blb #11 — Creature — Elemental Coyote
// When this creature enters, exile target creature an opponent controls until this creature leaves the battlefield. If that creature had power 2 or less, put a +1/+1 counter on this creature.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/driftgloom-coyote.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Driftgloom Coyote
// {3}{W}{W}  Creature Elemental Coyote  3/4

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(opp[0].getCreaturesInPlay()), 'Exile');  // Duration=UntilHostLeavesPlay
  if (you.getCardsIn('Battlefield').some((c) => c.hasSubtype('Creature'))) {
    putCounter(self, 'P1P1', 1);  // ConditionDefined=Targeted
  }
}
