// Eddymurk Crab
// Scryfall: blb #48 — Creature — Elemental Crab
// Flash
// This spell costs {1} less to cast for each instant and sorcery card in your graveyard.
// This creature enters tapped if it's not your turn.
// When this creature enters, tap up to two target creatures.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/eddymurk-crab.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Eddymurk Crab
// {5}{U}{U}  Creature Elemental Crab  5/5

// Keyword: Flash — may be cast any time you could cast an instant

/** Static: costs X less to cast (continuous). Continuous, not event-driven — no real executable body. */
export function staticEffect(self: Card, you: Player, opp: Player[]): void {
  // costs X less to cast (continuous)
}

// unmapped keyword: ETBReplacement(Other, LandTapped)

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  tap(chooseTarget(you.getCreaturesInPlay()));  // TargetMin=0, TargetMax=2
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Eddymurk Crab: K:ETBReplacement (params: Other:LandTapped) has no mapping yet
