// Eluge, the Shoreless Sea
// Scryfall: blb #49 — Legendary Creature — Elemental Fish
// Eluge's power and toughness are each equal to the number of Islands you control.
// Whenever Eluge enters or attacks, put a flood counter on target land. It's an Island in addition to its other types for as long as it has a flood counter on it.
// The first instant or sorcery spell you cast each turn costs {U} (or {1}) less to cast for each land you control with a flood counter on it.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/eluge-the-shoreless-sea.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Eluge, the Shoreless Sea
// {1}{U}{U}{U}  Legendary Creature Elemental Fish  */*

/** Static: power/toughness are each equal to X (characteristic-defining). Continuous, not event-driven — no real executable body. */
export function staticEffect(self: Card, you: Player, opp: Player[]): void {
  // power/toughness are each equal to X (characteristic-defining)
}

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  putCounter(chooseTarget(you.getLandsInPlay()), 'FLOOD', 1);
  // unmapped: Effect(RememberObjects=Targeted, StaticAbilities=FountainStatic, ForgetOnMoved=Battlefield, ForgetCounter=FLOOD, Duration=Permanent)
}

/**
 * Trigger: when this attacks.
 */
export function onAttacks(self: Card, you: Player, opp: Player[]): void {
  putCounter(chooseTarget(you.getLandsInPlay()), 'FLOOD', 1);
  // unmapped: Effect(RememberObjects=Targeted, StaticAbilities=FountainStatic, ForgetOnMoved=Battlefield, ForgetCounter=FLOOD, Duration=Permanent)
}

/** Static: costs Y less to cast (continuous). Continuous, not event-driven — no real executable body. */
export function staticEffect2(self: Card, you: Player, opp: Player[]): void {
  // costs Y less to cast (continuous)
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Eluge, the Shoreless Sea: effect "Effect" has no real-code builder yet
//   - Eluge, the Shoreless Sea: effect "Effect" has no real-code builder yet
