// Essence Channeler
// Scryfall: blb #12 — Creature — Bat Cleric
// As long as you've lost life this turn, this creature has flying and vigilance.
// Whenever you gain life, put a +1/+1 counter on this creature.
// When this creature dies, put its counters on target creature you control.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/essence-channeler.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Essence Channeler
// {1}{W}  Creature Bat Cleric  2/1

/** Static: any has "Flying & Vigilance" (continuous). Continuous, not event-driven — no real executable body. */
export function staticEffect(self: Card, you: Player, opp: Player[]): void {
  // any has "Flying & Vigilance" (continuous)
}

/**
 * Trigger: whenever You gains life.
 */
export function onLifeGained(self: Card, you: Player, opp: Player[]): void {
  putCounter(self, 'P1P1', 1);
}

/**
 * Trigger: when this dies (battlefield -> graveyard).
 */
export function onDies(self: Card, you: Player, opp: Player[]): void {
  putCounter(chooseTarget(you.getCreaturesInPlay()), 'EachFromSource', 1);  // EachFromSource=TriggeredCardLKICopy
}
