// Feather of Flight
// Scryfall: blb #13 — Enchantment — Aura
// Flash
// Enchant creature
// When this Aura enters, draw a card.
// Enchanted creature gets +1/+0 and has flying.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/feather-of-flight.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Feather of Flight
// {1}{W}  Enchantment Aura

// Keyword: Flash — may be cast any time you could cast an instant

// Enchant creature.

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  you.drawCard();
}

/** Static: enchanted creature gets +1/+0 (continuous). Continuous, not event-driven — no real executable body. */
export function staticEffect(self: Card, you: Player, opp: Player[]): void {
  // enchanted creature gets +1/+0 (continuous)
}
