// Finch Formation
// Scryfall: blb #50 — Creature — Bird Scout
// Flying
// When this creature enters, target creature you control gains flying until end of turn.
// (This token's mana cost is {2}{U}.)
// Generated by app/lib/functionalTranslate.ts from forge-model/data/finch-formation.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Finch Formation
// {2}{U}  Creature Bird Scout  2/2

// Offspring {3}: pay this as an additional cost as you cast this; if you do, when this enters, create a 1/1 token copy of it.

// Keyword: Flying — can only be blocked by flying or reach

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  pump(chooseTarget(you.getCreaturesInPlay()), 0, 0);  // KW=Flying
}
