// Flowerfoot Swordmaster
// Scryfall: blb #14 — Creature — Mouse Soldier
// Valiant — Whenever this creature becomes the target of a spell or ability you control for the first time each turn, Mice you control get +1/+0 until end of turn.
// (This token's mana cost is {W}.)
// Generated by app/lib/functionalTranslate.ts from forge-model/data/flowerfoot-swordmaster.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Flowerfoot Swordmaster
// {W}  Creature Mouse Soldier  1/2

// Offspring {2}: pay this as an additional cost as you cast this; if you do, when this enters, create a 1/1 token copy of it.

/**
 * Trigger: when this becomes the target of a spell/ability.
 * Only once per turn.
 */
export function onBecomesTarget(self: Card, you: Player, opp: Player[]): void {
  for (const c of you.getCardsIn('Battlefield')) {
    pump(c, +1, 0);
  }
}
