// Harvestrite Host
// Scryfall: blb #15 — Creature — Rabbit Citizen
// Whenever this creature or another Rabbit you control enters, target creature you control gets +1/+0 until end of turn. Then draw a card if this is the second time this ability has resolved this turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/harvestrite-host.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Harvestrite Host
// {2}{W}  Creature Rabbit Citizen  3/3

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  pump(chooseTarget(you.getCreaturesInPlay()), +1, 0);
  if (false /* unmapped: svar(Resolved EQ2) */) {
    you.drawCard();
  }
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Harvestrite Host: ConditionCheckSVar$/ConditionSVarCompare$ (Resolved EQ2) didn't fit the opp-vs-you X/Y shape
