// Hop to It
// Scryfall: blb #16 — Sorcery
// Create three 1/1 white Rabbit creature tokens.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/hop-to-it.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Hop to It
// {2}{W}  Sorcery

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  createToken(you, TOKENS.w_1_1_rabbit, 3);
}
