// Intrepid Rabbit
// Scryfall: blb #17 — Creature — Rabbit Soldier
// Offspring {1} (You may pay an additional {1} as you cast this spell. If you do, when this creature enters, create a 1/1 token copy of it.)
// When this creature enters, target creature you control gets +1/+1 until end of turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/intrepid-rabbit.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Intrepid Rabbit
// {2}{W}  Creature Rabbit Soldier  3/2

// Offspring {1}: pay this as an additional cost as you cast this; if you do, when this enters, create a 1/1 token copy of it.

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  pump(chooseTarget(you.getCreaturesInPlay()), +1, +1);
}
