// Jackdaw Savior
// Scryfall: blb #18 — Creature — Bird Cleric
// Flying
// Whenever this creature or another creature you control with flying dies, return another target creature card with lesser mana value from your graveyard to the battlefield.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/jackdaw-savior.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Jackdaw Savior
// {2}{W}  Creature Bird Cleric  3/1

// Keyword: Flying — can only be blocked by flying or reach

/**
 * Trigger: when this dies (battlefield -> graveyard).
 */
export function onDies(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(you.getCreaturesInPlay()), 'Battlefield');
}
