// Jolly Gerbils
// Scryfall: blb #19 — Creature — Hamster Citizen
// Whenever you give a gift, draw a card.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/jolly-gerbils.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Jolly Gerbils
// {1}{W}  Creature Hamster Citizen  2/3

/**
 * Trigger: when a gift is given.
 */
export function onGiftGiven(self: Card, you: Player, opp: Player[]): void {
  you.drawCard();
}
