// Lifecreed Duo
// Scryfall: blb #20 — Creature — Bat Bird
// Flying
// Whenever another creature you control enters, you gain 1 life.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/lifecreed-duo.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Lifecreed Duo
// {1}{W}  Creature Bat Bird  1/2

// Keyword: Flying — can only be blocked by flying or reach

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  you.gainLife(1, self);
}
