// Mabel's Mettle
// Scryfall: blb #21 — Instant
// Target creature gets +2/+2 until end of turn. Up to one other target creature gets +1/+1 until end of turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/mabel-s-mettle.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Mabel's Mettle
// {1}{W}  Instant

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  pump(chooseTarget(you.getCreaturesInPlay()), +2, +2);
  pump(chooseTarget(you.getCreaturesInPlay()), +1, +1);  // TargetMin=0, TargetMax=1, TargetUnique=True
}
