// Mouse Trapper
// Scryfall: blb #22 — Creature — Mouse Soldier
// Flash
// Valiant — Whenever this creature becomes the target of a spell or ability you control for the first time each turn, tap target creature an opponent controls.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/mouse-trapper.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Mouse Trapper
// {2}{W}  Creature Mouse Soldier  3/2

// Keyword: Flash — may be cast any time you could cast an instant

/**
 * Trigger: when this becomes the target of a spell/ability.
 * Only once per turn.
 */
export function onBecomesTarget(self: Card, you: Player, opp: Player[]): void {
  tap(chooseTarget(opp[0].getCreaturesInPlay()));
}
