// Nettle Guard
// Scryfall: blb #23 — Creature — Mouse Soldier
// Valiant — Whenever this creature becomes the target of a spell or ability you control for the first time each turn, it gets +0/+2 until end of turn.
// {1}, Sacrifice this creature: Destroy target artifact or enchantment.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/nettle-guard.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Nettle Guard
// {1}{W}  Creature Mouse Soldier  3/1

/**
 * Trigger: when this becomes the target of a spell/ability.
 * Only once per turn.
 */
export function onBecomesTarget(self: Card, you: Player, opp: Player[]): void {
  pump(self, 0, +2);
}

/** Cost: {1}, sacrifice a self. */
export function activated(self: Card, you: Player, opp: Player[]): void {
  destroy(chooseTarget(you.getCardsIn('Battlefield')));
}
