// Parting Gust
// Scryfall: blb #24 — Instant
// Gift a tapped Fish (You may promise an opponent a gift as you cast this spell. If you do, they create a tapped 1/1 blue Fish creature token before its other effects.)
// Exile target nontoken creature. If the gift wasn't promised, return that card to the battlefield under its owner's control with a +1/+1 counter on it at the beginning of the next end step.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/parting-gust.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Parting Gust
// {W}{W}  Instant

/** You may promise this to an opponent as an additional cost as you cast this. */
export function gift(self: Card, you: Player, opp: Player[]): void {
  createToken(opp[0], TOKENS.u_1_1_fish);  // TokenTapped=True, LockTokenScript=True, GiftDescription=a tapped Fish
}

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(you.getCreaturesInPlay()), 'Exile');  // RememberChanged=True
  if (false /* unmapped: the gift was not promised */) {
    // unmapped: DelayedTrigger(Phase=End of Turn, RememberObjects=RememberedLKI, ConditionZone=Stack)
  }
  moveTo(self /* unmapped: Defined$DelayTriggerRememberedLKI — not tracked, using self as a type-safe placeholder */, 'Battlefield');  // WithCountersType=P1P1
  // Cleanup: Forge-internal bookkeeping, no runtime action
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Parting Gust: gift-promised condition (gift_not_promised) has no gift-state representation in functional-model/interfaces.ts
//   - Parting Gust: effect "DelayedTrigger" has no real-code builder yet
//   - Parting Gust: Defined$DelayTriggerRememberedLKI refers to a previously chosen/remembered card, not tracked by this translator
