// Pileated Provisioner
// Scryfall: blb #25 — Creature — Bird Scout
// Flying
// When this creature enters, put a +1/+1 counter on target creature you control without flying.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/pileated-provisioner.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Pileated Provisioner
// {4}{W}  Creature Bird Scout  3/4

// Keyword: Flying — can only be blocked by flying or reach

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  putCounter(chooseTarget(you.getCreaturesInPlay()), 'P1P1', 1);
}
