// Rabbit Response
// Scryfall: blb #26 — Instant
// Creatures you control get +2/+1 until end of turn. If you control a Rabbit, scry 2. (Look at the top two cards of your library, then put any number of them on the bottom and the rest on top in any order.)
// Generated by app/lib/functionalTranslate.ts from forge-model/data/rabbit-response.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Rabbit Response
// {2}{W}{W}  Instant

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  for (const c of you.getCreaturesInPlay()) {
    pump(c, +2, +1);
  }
  if (you.getCardsIn('Battlefield').some((c) => c.hasSubtype('Rabbit'))) {
    scry(you, 1);  // ScryNum=2
  }
}
