// Repel Calamity
// Scryfall: blb #27 — Instant
// Destroy target creature with power or toughness 4 or greater.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/repel-calamity.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Repel Calamity
// {1}{W}  Instant

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  destroy(chooseTarget(you.getCreaturesInPlay()));
}
