// Salvation Swan
// Scryfall: blb #28 — Creature — Bird Cleric
// Flash
// Flying
// Whenever this creature or another Bird you control enters, exile up to one target creature you control without flying. Return it to the battlefield under its owner's control with a flying counter on it at the beginning of the next end step.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/salvation-swan.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Salvation Swan
// {3}{W}  Creature Bird Cleric  3/3

// Keyword: Flash — may be cast any time you could cast an instant

// Keyword: Flying — can only be blocked by flying or reach

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  moveTo(chooseTarget(you.getCreaturesInPlay()), 'Exile');  // TargetMin=0, TargetMax=1, RememberChanged=True
  if (false /* unmapped: ConditionPresent existence check, no specific subtype */) {
    // unmapped: DelayedTrigger(Phase=End of Turn, RememberObjects=RememberedLKI, ConditionDefined=Remembered)
  }
  moveTo(self /* unmapped: Defined$DelayTriggerRememberedLKI — not tracked, using self as a type-safe placeholder */, 'Battlefield');  // WithCountersType=Flying
  // Cleanup: Forge-internal bookkeeping, no runtime action
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Salvation Swan: ConditionPresent$ existence check has no specific subtype to test (coarseType -> "any")
//   - Salvation Swan: effect "DelayedTrigger" has no real-code builder yet
//   - Salvation Swan: Defined$DelayTriggerRememberedLKI refers to a previously chosen/remembered card, not tracked by this translator
