// Seasoned Warrenguard
// Scryfall: blb #30 — Creature — Rabbit Warrior
// Whenever this creature attacks while you control a token, this creature gets +2/+0 until end of turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/seasoned-warrenguard.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Seasoned Warrenguard
// {W}  Creature Rabbit Warrior  1/2

/**
 * Trigger: when this attacks.
 */
export function onAttacks(self: Card, you: Player, opp: Player[]): void {
  pump(self, +2, 0);
}
