// Season of the Burrow
// Scryfall: blb #29 — Sorcery
// Choose up to five {P} worth of modes. You may choose the same mode more than once.
// {P} — Create a 1/1 white Rabbit creature token.
// {P}{P} — Exile target nonland permanent. Its controller draws a card.
// {P}{P}{P} — Return target permanent card with mana value 3 or less from your graveyard to the battlefield with an indestructible counter on it.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/season-of-the-burrow.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Season of the Burrow
// {3}{W}{W}  Sorcery

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[], mode: number): void {
  if (mode === 1) {
    createToken(you, TOKENS.w_1_1_rabbit);  // Pawprint=1
  } else if (mode === 2) {
    moveTo(chooseTarget(you.getCardsIn('Battlefield')), 'Exile');  // Pawprint=2, RememberLKI=True
    you.drawCard();
    // Cleanup: Forge-internal bookkeeping, no runtime action
  } else {
    moveTo(chooseTarget(you.getCardsIn('Battlefield')), 'Battlefield');  // Pawprint=3, WithCountersType=Indestructible
  }
}
