// Shrike Force
// Scryfall: blb #31 — Creature — Bird Knight
// Flying, double strike, vigilance
// Generated by app/lib/functionalTranslate.ts from forge-model/data/shrike-force.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Shrike Force
// {2}{W}  Creature Bird Knight  1/3

// Keyword: Flying — can only be blocked by flying or reach

// Keyword: Double Strike — deals both first-strike and regular combat damage

// Keyword: Vigilance — doesn't tap to attack
