// Sonar Strike
// Scryfall: blb #32 — Instant
// Sonar Strike deals 4 damage to target attacking, blocking, or tapped creature. You gain 3 life if you control a Bat.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/sonar-strike.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Sonar Strike
// {1}{W}  Instant

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  dealDamage(self, chooseTarget(you.getCreaturesInPlay()), 4);
  if (you.getCardsIn('Battlefield').some((c) => c.hasSubtype('Bat'))) {
    you.gainLife(3, self);
  }
}
