// Star Charter
// Scryfall: blb #33 — Creature — Bat Cleric
// Flying
// At the beginning of your end step, if you gained or lost life this turn, look at the top four cards of your library. You may reveal a creature card with power 3 or less from among them and put it into your hand. Put the rest on the bottom of your library in a random order.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/star-charter.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Star Charter
// {3}{W}  Creature Bat Cleric  3/1

// Keyword: Flying — can only be blocked by flying or reach

/**
 * Trigger: at End of Turn.
 */
export function onPhase(self: Card, you: Player, opp: Player[]): void {
  const cr112 = dig(you, 1);  // DigNum=4, ChangeNum=1, Optional=True, ForceRevealToController=True, ChangeValid=Creature.powerLE3, RestRandomOrder=True
}
