// Starfall Invocation
// Scryfall: blb #34 — Sorcery
// Gift a card (You may promise an opponent a gift as you cast this spell. If you do, they draw a card before its other effects.)
// Destroy all creatures. If the gift was promised, return a creature card put into your graveyard this way to the battlefield under your control.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/starfall-invocation.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Starfall Invocation
// {3}{W}{W}  Sorcery

/** You may promise this to an opponent as an additional cost as you cast this. */
export function gift(self: Card, you: Player, opp: Player[]): void {
  opp[0].drawCard();  // GiftDescription=a card
}

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  for (const c of you.getCreaturesInPlay()) {
    destroy(c);
  }  // RememberDestroyed=True
  if (false /* unmapped: the gift was promised */) {
    moveTo(self, 'Battlefield');  // ConditionZone=Stack, ChangeType=Creature.!token+IsRemembered+YouOwn, ChangeNum=1, Hidden=True, Mandatory=True
  }
  // Cleanup: Forge-internal bookkeeping, no runtime action
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Starfall Invocation: gift-promised condition (gift_promised) has no gift-state representation in functional-model/interfaces.ts
