// The Final Days
// Scryfall: fin #101 — Sorcery
// Create two tapped 2/2 black Horror creature tokens. If this spell was cast from a graveyard, instead create X of those tokens, where X is the number of creature cards in your graveyard.
// Flashback {4}{B}{B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
// Generated by app/lib/functionalTranslate.ts from forge-model/data/the-final-days.txt — AI output, not human-reviewed.
// NOTE: outside functional-model/README.md's declared BLB-1-50 scope — a one-off requested to see how Flashback renders.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// The Final Days
// {2}{B}{B}  Sorcery

// Flashback {4}{B}{B}: may cast this card from your graveyard for this cost, then exile it instead of it going to the graveyard again.

/** This spell's own printed effect. */
export function onCast(self: Card, you: Player, opp: Player[]): void {
  createToken(you, TOKENS.b_2_2_horror, 1);  // TokenTapped=True, TokenAmount=Y
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - The Final Days: TokenAmount$Y is a dynamic SVar, not a literal count — defaulted to 1
