// Thistledown Players
// Scryfall: blb #35 — Creature — Mouse Bard
// Whenever this creature attacks, untap target nonland permanent.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/thistledown-players.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Thistledown Players
// {2}{W}  Creature Mouse Bard  3/3

/**
 * Trigger: when this attacks.
 */
export function onAttacks(self: Card, you: Player, opp: Player[]): void {
  untap(chooseTarget(you.getCardsIn('Battlefield')));
}
