// Valley Questcaller
// Scryfall: blb #36 — Creature — Rabbit Warrior
// Whenever one or more other Rabbits, Bats, Birds, and/or Mice you control enter, scry 1.
// Other Rabbits, Bats, Birds, and Mice you control get +1/+1.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/valley-questcaller.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Valley Questcaller
// {1}{W}  Creature Rabbit Warrior  2/3

/**
 * Trigger: when this enters the battlefield.
 */
export function onEnter(self: Card, you: Player, opp: Player[]): void {
  scry(you, 1);  // ScryNum=1
}

/** Static: rabbit gets +1/+1 (continuous). Continuous, not event-driven — no real executable body. */
export function staticEffect(self: Card, you: Player, opp: Player[]): void {
  // rabbit gets +1/+1 (continuous)
}
