// Warren Warleader
// Scryfall: blb #38 — Creature — Rabbit Knight
// Offspring {2} (You may pay an additional {2} as you cast this spell. If you do, when this creature enters, create a 1/1 token copy of it.)
// Whenever you attack, choose one —
// • Create a 1/1 white Rabbit creature token that's tapped and attacking.
// • Attacking creatures you control get +1/+1 until end of turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/warren-warleader.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Warren Warleader
// {2}{W}{W}  Creature Rabbit Knight  4/4

// Offspring {2}: pay this as an additional cost as you cast this; if you do, when this enters, create a 1/1 token copy of it.

/**
 * Trigger: when attackers are declared.
 */
export function onAttackersDeclared(self: Card, you: Player, opp: Player[], mode: number): void {
  if (mode === 1) {
    createToken(you, TOKENS.w_1_1_rabbit);  // TokenTapped=True, TokenAttacking=True
  } else {
    for (const c of you.getCreaturesInPlay()) {
      pump(c, +1, +1);
    }
  }
}
