// Warren Elder
// Scryfall: blb #37 — Creature — Rabbit Cleric
// {3}{W}: Creatures you control get +1/+1 until end of turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/warren-elder.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Warren Elder
// {1}{W}  Creature Rabbit Cleric  2/2

/** Cost: {3}{W}. */
export function activated(self: Card, you: Player, opp: Player[]): void {
  for (const c of you.getCreaturesInPlay()) {
    pump(c, +1, +1);
  }
}
