// Wax-Wane Witness
// Scryfall: blb #39 — Creature — Bat Cleric
// Flying, vigilance
// Whenever you gain or lose life during your turn, this creature gets +1/+0 until end of turn.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/wax-wane-witness.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Wax-Wane Witness
// {3}{W}  Creature Bat Cleric  2/4

// Keyword: Flying — can only be blocked by flying or reach

// Keyword: Vigilance — doesn't tap to attack

/**
 * Trigger: whenever You gains life.
 */
export function onLifeGained(self: Card, you: Player, opp: Player[]): void {
  pump(self, +1, 0);
}

/**
 * Trigger: whenever You loses life.
 */
export function onLifeLost(self: Card, you: Player, opp: Player[]): void {
  pump(self, +1, 0);
}
