// Whiskervale Forerunner
// Scryfall: blb #40 — Creature — Mouse Bard
// Valiant — Whenever this creature becomes the target of a spell or ability you control for the first time each turn, look at the top five cards of your library. You may reveal a creature card with mana value 3 or less from among them. You may put it onto the battlefield if it's your turn. If you don't put it onto the battlefield, put it into your hand. Put the rest on the bottom of your library in a random order.
// Generated by app/lib/functionalTranslate.ts from forge-model/data/whiskervale-forerunner.txt — AI output, not human-reviewed.

import type { Card, Player } from '../interfaces';
import {
  createToken, destroy, sacrifice, dealDamage, putCounter, tap, untap, mill, scry, surveil, dig, discard,
  exile, moveTo, gainControl, pump, copyPermanent, play, controls, chooseTarget, highest, isYourTurn,
} from '../interfaces';
import { TOKENS } from '../tokens';

// Whiskervale Forerunner
// {3}{W}  Creature Mouse Bard  3/4

/**
 * Trigger: when this becomes the target of a spell/ability.
 * Only once per turn.
 */
export function onBecomesTarget(self: Card, you: Player, opp: Player[]): void {
  // unmapped: PeekAndReveal(Defined=You, PeekAmount=5, NoReveal=True, RememberPeeked=True)
  // unmapped: ChooseCard(Defined=You, Amount=1, ChoiceTitle=Choose a creature card to reveal, ChoiceZone=Library, Reveal=True)
  // unmapped: choose one — no resolvable branches (Choices$ wasn't a list of SVar names)
  if (false /* unmapped: ConditionPresent existence check, no specific subtype */) {
    moveTo(self /* unmapped: Defined$ChosenCard — not tracked, using self as a type-safe placeholder */, 'Battlefield');  // ConditionPlayerTurn=True, ConditionDefined=Remembered, Optional=True
  }
  if (false /* unmapped: ConditionPresent existence check, no specific subtype */) {
    moveTo(self /* unmapped: Defined$ChosenCard — not tracked, using self as a type-safe placeholder */, 'Hand');  // ConditionDefined=Remembered
  }
  for (const c of you.getCardsIn('Battlefield')) {
    moveTo(c, 'Library');
  }  // ChangeType=Card.IsRemembered, LibraryPosition=-1, RandomOrder=True
  // Cleanup: Forge-internal bookkeeping, no runtime action
}

// Unmapped (this translator has no handling for these — see the note next to each):
//   - Whiskervale Forerunner: effect "PeekAndReveal" has no real-code builder yet
//   - Whiskervale Forerunner: effect "ChooseCard" has no real-code builder yet
//   - Whiskervale Forerunner: Choices$ group has no resolvable branches (not a Charm-style SVar-name list — see this function's own comment)
//   - Whiskervale Forerunner: ConditionPresent$ existence check has no specific subtype to test (coarseType -> "any")
//   - Whiskervale Forerunner: Defined$ChosenCard refers to a previously chosen/remembered card, not tracked by this translator
//   - Whiskervale Forerunner: ConditionPresent$ existence check has no specific subtype to test (coarseType -> "any")
//   - Whiskervale Forerunner: Defined$ChosenCard refers to a previously chosen/remembered card, not tracked by this translator
