// Regenerates functional-model/data/*.ts for BLB collector numbers 1-50 —
// see functional-model/README.md for what this is and why. Modeled on
// synergy-model/scripts/make-exam-forge.mjs's own "plain script imports
// app/lib/*.ts directly" pattern, with one difference: make-exam-forge.mjs
// only ever imports forgeScript.ts/forgeTranslate.ts, both of which
// deliberately avoid extensionless cross-imports INTO each other (see
// forgeTranslate.ts's own top-of-file comment on why — plain `node`'s native
// TS support only resolves module specifiers Node's own resolver
// understands, which doesn't include extensionless relative imports the way
// Vite/Nuxt/Vitest's bundler-style resolution does). app/lib/functionalTranslate.ts
// intentionally DOES import several helpers from forgeTranslate.ts
// extensionless (reuse, not duplication, of its already-solved Forge-
// semantics helpers — see that file's own header) to stay consistent with
// every other in-repo consumer of it (Nuxt pages, vitest). That means THIS
// script can't use plain `node` the way make-exam-forge.mjs does — it needs
// vite-node's bundler-style resolution instead (already present via the
// vitest devDependency, no new dependency added).
//
// Usage: npx vite-node functional-model/scripts/generate.mjs

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';

const { parseForgeScript } = await import('../../app/lib/forgeScript.ts');
const { translateForgeToFunctional } = await import('../../app/lib/functionalTranslate.ts');

function slugify(word) {
  return word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

const pool = JSON.parse(await readFile('forge-model/pools/blb.json', 'utf8'));
const cards = pool.filter((c) => parseInt(c.collectorNumber, 10) <= 50);
console.log(`Generating functional-model for ${cards.length} BLB cards (collector numbers 1-50).`);

// Step 4 — real printed oracle text, purely for the header comment a human
// reads alongside the generated pseudocode (NOT fed into the translator
// itself, which only ever reads the Forge script, same as
// app/lib/forgeTranslate.ts does). This is a real Scryfall bulk-data dump —
// one row per distinct card name, not per printing — so a name lookup here
// is exact-match against `oracle_text` (or, for a DFC/split card, each
// face's own text joined the way Scryfall itself displays them).
async function loadOracleTextByName() {
  console.log('Reading Scryfall oracle-cards bulk dump (one-time, ~24MB gzipped)...');
  const gz = await readFile('tagging/scryfall-bulk/oracle-cards-20260830090156.jsonl.gz');
  const raw = gunzipSync(gz).toString('utf8');
  const byName = new Map();
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    let entry;
    try {
      entry = JSON.parse(line);
    } catch {
      continue;
    }
    const text = entry.card_faces?.length
      ? entry.card_faces.map((f) => f.oracle_text).filter(Boolean).join('\n// --\n')
      : entry.oracle_text;
    if (text) byName.set(entry.name, text);
  }
  return byName;
}

let oracleByName;
try {
  oracleByName = await loadOracleTextByName();
} catch (err) {
  console.warn(`Could not load oracle text bulk dump (${err.message}) — generating without it.`);
  oracleByName = new Map();
}

await mkdir('functional-model/data', { recursive: true });

const clean = [];
const withGaps = [];

for (const card of cards) {
  const slug = slugify(card.name);
  const forgeRaw = await readFile(`forge-model/data/${slug}.txt`, 'utf8').catch(() => null);
  if (!forgeRaw) {
    console.error(`MISSING forge-model/data/${slug}.txt for "${card.name}" — skipping (should not happen, see forge-model/README.md).`);
    continue;
  }

  const parsed = parseForgeScript(forgeRaw);
  const { code, unmapped } = translateForgeToFunctional(parsed);

  const header = [`// ${card.name}`, `// Scryfall: blb #${card.collectorNumber} — ${card.typeLine}`];
  const oracle = oracleByName.get(card.name);
  if (oracle) header.push(...oracle.split('\n').map((l) => `// ${l}`));
  header.push('// Generated by app/lib/functionalTranslate.ts from forge-model/data/' + `${slug}.txt — AI output, not human-reviewed.`);
  header.push('');

  const footer =
    unmapped.length > 0
      ? ['', '// Unmapped (this translator has no handling for these — see the note next to each):', ...unmapped.map((u) => `//   - ${u}`)]
      : [];

  // `code` already carries its own import header (interfaces.ts/tokens.ts) — the
  // card-name/oracle-text header above is prepended as leading comments
  // before it, same layout the old .txt output used.
  const out = [...header, code.trimEnd(), ...footer].join('\n') + '\n';
  await writeFile(`functional-model/data/${slug}.ts`, out, 'utf8');

  if (unmapped.length === 0) clean.push(card.name);
  else withGaps.push({ name: card.name, unmapped });
}

console.log('');
console.log(`Done. ${clean.length + withGaps.length} files written.`);
console.log(`  ${clean.length} with zero unmapped entries.`);
console.log(`  ${withGaps.length} with at least one unmapped entry:`);
for (const { name, unmapped } of withGaps) {
  console.log(`    - ${name} (${unmapped.length}): ${unmapped[0]}${unmapped.length > 1 ? ` [+${unmapped.length - 1} more]` : ''}`);
}
