// Production data source for functional-model/cards/<slug>/'s generated
// artifacts (synergy.json/trace.json/progress.json) plus the handful of
// real CardDefinition fields (name/manaCost/typeLine/cmc/pt) the cross-card
// matcher needs — see scripts/build-fm-bundle.mjs's own header for why this
// exists and how it's built. A plain STATIC JSON import (same pattern
// server/api/card/[set]/[number].ts already uses for data/global_relations.json
// et al.) so Nitro/Rollup traces and bundles it into the Netlify Function at
// build time — unlike a readFileSync/readdirSync/dynamic-import() against
// the raw functional-model/ source tree, which never survives that bundle
// (confirmed in prod as ENOENT scandir '/var/task/functional-model').
//
// Consumed by both server/api/card/[set]/[number].ts (per-card
// FunctionalModelData, production branch of loadFunctionalModel) and
// server/utils/functionalModelPool.ts (whole-pool PoolCard[], production
// branch of loadFunctionalModelPool) — the exact same two request-time
// readers this bundle exists to unblock in prod. Dev keeps reading the raw
// source tree live (definition.ts/scenarios.ts/synergy.json edits show up
// immediately, no `npm run sync:fm-bundle` step needed) — this bundle is
// only ever read when NODE_ENV==='production'.
//
// Re-run `npm run sync:fm-bundle` (scripts/build-fm-bundle.mjs) and commit
// the diff whenever functional-model/cards/ changes — same manual
// "regenerate, then commit" cadence synergy.json/trace.json/progress.json
// themselves already have via functional-model/scripts/*.mjs. This file
// does NOT auto-regenerate on `npm run build`; a stale bundle after an
// engine-side card edit means prod keeps serving the LAST COMMITTED
// snapshot until this is re-run, same staleness contract synergy.json/
// trace.json already carry for their own consumers.
import fmBundleJson from '../../data/functional-model/fm-bundle.json';
import type { Fact } from '../../functional-model/synergy';
import type { CardDefinition } from '../../functional-model/card';
import type { TraceResult } from '../../functional-model/harness';

export interface FmBundleEntry {
  name: string;
  // Structurally a CardDefinition (name/manaCost/typeLine required, cmc/pt
  // optional) — never `effects`/`triggers`/etc, which functional-model/
  // synergy.ts's matcher (staticAttrsFor/resolveSubject, the only readers of
  // `PoolCard.card`) never reads; see build-fm-bundle.mjs's own comment for
  // the exact `.card.` access audit this relies on. Also carries
  // `continuousKeywordGrants` (+ a minimal `backFace` mirror of the same
  // field) — 2026-09-12, ENGINE_GAPS.md gap #14 — read by
  // server/api/card/[set]/[number].ts's own `loadFunctionalModel` to serve
  // `FunctionalModelData.continuousKeywordGrants`, NOT by the synergy
  // matcher.
  poolFacts: CardDefinition;
  synergy: { source: Fact[]; sink: Fact[] } | null;
  traces: TraceResult[];
  review: 'ai' | 'human';
  scenariosReview: 'draft' | 'reviewed';
  interactionsReview: 'draft' | 'reviewed';
  source: string;
}

// Cast rather than let TS infer the raw JSON shape (tuple fields like
// `pt: [number, number]` come back as plain `number[]` from a JSON import,
// among other narrowing losses) — this file is generated by
// scripts/build-fm-bundle.mjs from the exact same source types, so the
// assertion just restates what's already true instead of re-deriving it via
// structural inference.
export const fmBundle = fmBundleJson as unknown as Record<string, FmBundleEntry>;
