// Dev-only reader for the Forge-corpus schema-vocabulary aggregate report —
// 2026-09-19, `/app/engine/schema-forge` reference page. Generated by a
// one-off analysis script (not committed, not part of any pipeline) that
// walked the FULL Forge card corpus (33,798 real cards, all of Magic's
// history) via `functional-model/scripts/experiments/forge-json-mapper/`'s
// own JSON mapper, then aggregated the observed shape/type vocabulary —
// every top-level field, every ability-line param, every SVar param, every
// keyword name, with frequency counts, plus type-consistency conflicts and
// structural gotchas. Groundwork for a possible future Forge-JSON ->
// `functional-model/card.ts` compiler — not that compiler itself.
//
// Lives at `tmp/forge-json-mapper-full-run/schema_aggregate.md`, gitignored
// (the whole `tmp/` tree, same as `tmp/mtg-forge/`) — explicit user
// constraint: "Forge stuff would be only locally for now". Won't exist on a
// fresh checkout, in CI, or in production. Same dev-only posture as
// `forgeScript.ts` (`tmp/mtg-forge/` reader): gated on
// `process.env.NODE_ENV !== 'production'` here AND defensively refused a
// second time inside this module itself, not just left to callers behaving.
// Missing-file case (script never run locally, or output since deleted) is
// expected/routine, not exceptional — this returns a plain "not available"
// result rather than throwing.
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface ForgeSchemaAggregateFound {
  available: true;
  content: string;
  // Repo-relative, for display only.
  path: string;
}
export interface ForgeSchemaAggregateNotFound {
  available: false;
  reason: 'dev-only' | 'not-found';
}
export type ForgeSchemaAggregateResult = ForgeSchemaAggregateFound | ForgeSchemaAggregateNotFound;

export function loadForgeSchemaAggregate(root: string = process.cwd()): ForgeSchemaAggregateResult {
  if (process.env.NODE_ENV === 'production') return { available: false, reason: 'dev-only' };

  const rel = join('tmp', 'forge-json-mapper-full-run', 'schema_aggregate.md');
  const abs = join(root, rel);
  if (!existsSync(abs)) return { available: false, reason: 'not-found' };

  try {
    return { available: true, content: readFileSync(abs, 'utf8'), path: rel };
  } catch {
    return { available: false, reason: 'not-found' };
  }
}
